### ISSUE TITLE
Compiled release

### ISSUE THREAD

**Issue by mrdeadlocked** [DrParanoia/ed-rgb#2]
Does this have a compiled release somewhere?

**Comment by TomW1605** [comment]
not as yet but i can upload one if needed. be awair that there are are sevral issues with the program in its curent state. also note that my copy will be from [my dev branch](https://github.com/DrParanoia/ed-rgb/tree/tom_develop). let me know if you want me to upload a .exe file.

**Comment by mrdeadlocked** [comment]
yes. I would love to try it out. Just getting into elite dangerous and have the g910. :-)

**Comment by TomW1605** [comment]
hi
unfortunatly i couldent make a .exe but i have uploaded the .jar and that should work just fine.
i am not 100% sure that all the depenendanceys are included but i think they are. if you have any trouble let me know.
here is the link https://github.com/DrParanoia/ed-rgb/raw/tom_develop/ed-logitech-rgb.jar

**Comment by mrdeadlocked** [comment]
I downloaded it and it started fine. I'm getting this in the window when trying to use it with elite dangerous.

https://pastebin.com/PA1hmtey

I bet I am just missing something simple. Thanks for the help!

**Comment by TomW1605** [comment]
it looks like it is having trouble finding your bindings file. can you send a photo of your binds directory. also what is its full path? also what is in `StartPreset.start`?

**Comment by mrdeadlocked** [comment]
Okay. I was running the jar from my downloads folder. WHere do I find the binds directory and what is StartPreset,.start? :-)

**Comment by TomW1605** [comment]
you should be able to run it from anywhere. the binds folder is normaley `C:\Users\username\AppData\Local\Frontier Developments\Elite Dangerous\Options\Bindings` and that is where the program looks. the `StartPreset.start` file should be in there too. lastly could you go in game and check what binding preset you are using.

**Comment by mrdeadlocked** [comment]
![image](https://user-images.githubusercontent.com/461352/58370267-8fa99b80-7ed2-11e9-9221-d19f78148dda.png)

The StartPreset.start just says 'KeyboardMouseOnly' inside of it. Ingame I have keyboardandmouse selected in the dropdown.

**Comment by TomW1605** [comment]
ok it looks like you are using the default preset. we kind of assumed that anyone using this program would be using custom bindings. 2 things you can try. first run the jar then open ED. then go to the settings, change the preset to anything else, apply, and change it back again. if that does not work then find a bind that you never use and change it to something else to create a custom set of bindings. also check that there is a file called `Status.json` in `C:\Users\username\Saved Games\Frontier Developments\Elite Dangerous`.

**Comment by mrdeadlocked** [comment]
I did what you said and made a custom keybinding. This is what the log says. My keyboard doesn't seem to change tho. This is what the log shows when im actively playing ED.

![image](https://user-images.githubusercontent.com/461352/58376654-4cd0dd80-7f3d-11e9-9302-b3c625b3f4d7.png)

**Comment by TomW1605** [comment]
honestly im stumped and have exams coming up so if you can give me some time i will look into it. also did you find the `Status.json` file?

**Comment by TomW1605** [comment]
also not sure if this will make a difference but do you have LGS or GHUB installed?

**Comment by TomW1605** [comment]
ok i have had another look and i still think it is a problem with finding the binding. can you send another photo of your binds folder and confirm the current contents of the `StartPreset.start` file?

**Comment by mrdeadlocked** [comment]
No rush. If you'd like to work this issue out over discord or something let me know. Could be a lil easier.
![image](https://user-images.githubusercontent.com/461352/58382701-7fa9be80-7f9b-11e9-90a5-d82b0f424dc7.png)

StartPreset.start has Custom in it. I do have ghub installed.

**Comment by TomW1605** [comment]
yes discord would probabley be easier my discord name is Tom#7765. also odd request could you send me your custom binds file so i can test with it?

**Comment by TomW1605** [comment]
ok i think i fixed the issues. please redownload with the link above. i am going to close this issue now but if you have any more problems hit me up on discord. (also i think there is a large time zone difference between us)
