### ISSUE TITLE
LED Pattern stucked

### ISSUE THREAD

**Issue by feiercrack** [DrParanoia/ed-rgb#4]
from exiting an star port until fsd charging, your overlay works a bit.

after fsd is charged, the nice animation starts, then it loops in the "star rain" pattern, like here, 

https://youtu.be/AvofpV3bcjU?t=37

and never changing back to nomal pattern. i have to quit the app and restart. 

then it never changed when swapping over to any map, like star map or galaxy map... 

when i use star map, nothing changes on my keyboard...

**Comment by TomW1605** [comment]
ok i thought i fixed that issue. if i remember coreclty it had somthing to do with other programs i had running. can you give me a list of all the other programs you run and i will have a look.

**Comment by feiercrack** [comment]
and in taskbar:
Steam
Logitech GHUB
Ditto
EarTrumpet
Gyazo
O&O Defrag

**Comment by TomW1605** [comment]
i have had a bit of trouble recreating the issue. how often does it happen to you?
i unfortunatly dont have the same progreams as you but i dident have an issue with the ones i have (see below). there is one thing that i think could be causing it that i have fixed but cant test. if you could redownload the .jar and try again with as few other programs open as posabel that would be good. also if it does keep happening could you make a note of starting system, where you jumped from (normal space or supercruse), destination system and destination star type.
do u use any downloaded/complex voice attack profiles (like the HCS ones) or just ones that you have made?

programs i teseted with:
discord
EDDiscovery
EDEngineer
EDMarketConnector
VoiceAttack (with HCS profiles)
LGS (not GHUB, this might be a problem but dont think so)
i also havent tested recently with a HOTAS and its acompaneying software so you might want to try without that if posable.

**Comment by feiercrack** [comment]
i never came over that step. it never runned normal as it should in your video.

it always ends in this loop, after jump. only the "rain" effect i can see, and it stays in this loop.

i have astra voice pack (eng) and my personal integrated commands via voiceattack (eddi included)

tomorrow i will look after it

**Comment by feiercrack** [comment]
hi,

i never came over that step. it never runned normal as it should in your
video.

it always ends in this loop, after jump. only the "rain" effect i can see,
and it stands in this loop.

i have astra voice pack (eng) and my personal integrated commands via
voiceattack (eddi included)

tomorrow i will look after it

thanxxx

cheers^^

Am Mi., 14. Aug. 2019 um 16:07 Uhr schrieb Thomas White <
notifications@github.com>:

**Comment by feiercrack** [comment]
seems to be ok right now. i had another little issue after an jump. i restarted the game and now looks like that everything is alright. thank you!

**Comment by TomW1605** [comment]
sorry for the late reply.
great to here that it is working. you mentioned that there were also issues when changing to map, if that is still a problem can you please create a new issue for that? thanks
